config/routes.rb
Rails.application.routes.draw do
  resources :stss_trades
  get  '/', to: 'monte_carlo#new'
#  post '/', to: 'monte_carlo#create'
  post '/monte_carlo/new', to: 'monte_carlo#create'
  get '/show', to: 'monte_carlo#show'
  root :to => 'monte_carlo#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/monte_carlo.rb
class  MonteCarlo
#  include ActiveModel::Validations
#  include ActiveModel::Conversion
#  extend ActiveModel::Naming

  include ActiveAttr::BasicModel
  include ActiveAttr::Attributes
  include ActiveAttr::AttributeDefaults
  include ActiveAttr::QueryAttributes
  include ActiveAttr::TypecastedAttributes

  attribute :start_date, :type => Date, :default => Date.strptime("04/11/1996", "%m/%d/%Y")
  attribute :end_date, :type => Date, :default => Date.strptime("01/24/2012", "%m/%d/%Y")
  attribute :runs, :type => Integer, :default => 1000
  attribute :trade_type, :default => 'A'
  attribute :starting_amount, :default => 10000
  attribute :minimum_price, :default => 0
  attribute :maximum_price, :default => 999999
  attribute :max_picks, :type => Integer, :default => 16
  attribute :commission, :default => 7

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :runs, numericality: {only_integer: true}
  validates :runs, numericality: {:greater_than  => 0}
  validates :trade_type, presence: true
  validates :starting_amount, numericality: {:greater_than_or_equal_to  => 1000}
  validates :minimum_price, numericality: {:greater_than_or_equal_to  => 0}
  validates :maximum_price, numericality: {:greater_than  => :minimum_price}
  validates :max_picks, numericality: {only_integer: true}
  validates :max_picks, numericality: {:greater_than  => 0}
  validates :commission, numericality: {:greater_than_or_equal_to  => 0}

  validates :start_date, date: {
    after_or_equal_to: StssTrade.order(:buy_date).first(1)[0].buy_date}
  validates :start_date, date: {
    #before_or_equal_to: StssTrade.order(:buy_date).last(1)[0].buy_date}
    before_or_equal_to: Date.strptime("01/20/2012", "%m/%d/%Y")}

  validates :end_date, date: {after: :start_date}
  validates :end_date, date: {
    before_or_equal_to: Date.strptime("01/24/2012", "%m/%d/%Y")}

end

app/models/stss_trade.rb
class StssTrade < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/monte_carlo_controller.rb
# app/controllers/monte_carlo_controller.rb
class MonteCarloController < ApplicationController
  before_action :set_monte_carlo, only: [:show, :edit, :update, :destroy]

  # GET /monte_carlo/new
  def new
    @monte_carlo = MonteCarlo.new
#    @monte_carlo = MonteCarlo.new(params[:monte_carlo])
  end

  # POST /monte_carlo
  def create
    @monte_carlo = MonteCarlo.new(monte_carlo_params)
    puts @monte_carlo.runs
    if @monte_carlo.valid?
#      redirect to @monte_carlo, notice: 'Monte_carlo submission success'
      redirect_to action: "show", notice: 'Monte_carlo submission success'
    else
      render :action => "new"
    end
  end

  def show
  end

  def edit
  end

  private

    def set_monte_carlo
      @monte_carlo = MonteCarlo.new(params[:monte_carlo])
    end

    def monte_carlo_params
      params.fetch(:monte_carlo, {})
    end

end

app/controllers/stss_trades_controller.rb
class StssTradesController < ApplicationController
  before_action :set_stss_trade, only: [:show, :edit, :update, :destroy]

  # GET /stss_trades
  # GET /stss_trades.json
  def index
    @stss_trades = StssTrade.order(:id).page params[:page]
  end

  # GET /stss_trades/1
  # GET /stss_trades/1.json
  def show
  end

  # GET /stss_trades/new
  def new
    @stss_trade = StssTrade.new
  end

  # GET /stss_trades/1/edit
  def edit
  end

  # POST /stss_trades
  # POST /stss_trades.json
  def create
    @stss_trade = StssTrade.new(stss_trade_params)

    respond_to do |format|
      if @stss_trade.save
        format.html { redirect_to @stss_trade, notice: 'Stss trade was successfully created.' }
        format.json { render :show, status: :created, location: @stss_trade }
      else
        format.html { render :new }
        format.json { render json: @stss_trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stss_trades/1
  # PATCH/PUT /stss_trades/1.json
  def update
    respond_to do |format|
      if @stss_trade.update(stss_trade_params)
        format.html { redirect_to @stss_trade, notice: 'Stss trade was successfully updated.' }
        format.json { render :show, status: :ok, location: @stss_trade }
      else
        format.html { render :edit }
        format.json { render json: @stss_trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stss_trades/1
  # DELETE /stss_trades/1.json
  def destroy
    @stss_trade.destroy
    respond_to do |format|
      format.html { redirect_to stss_trades_url, notice: 'Stss trade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stss_trade
      @stss_trade = StssTrade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stss_trade_params
      params.fetch(:stss_trade, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monte_carlo_helper.rb
module MonteCarloHelper
end

app/helpers/stss_trades_helper.rb
module StssTradesHelper
end

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StssApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Monte Carlo Simulation"

    = stylesheet_link_tag 'application', media: 'all',
      'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/shim'
    = csrf_meta_tag

  body

    == yield

app/views/monte_carlo/_form.html.slim
= form_for :monte_carlo do |f|
  - if @monte_carlo.errors.any?
    div id="error_explanation"
      h2 = pluralize(monte_carlo.errors.count, "error")
      | prohibited this monte_carlo from being run:

      ul
       - @monte_carlo.errors.full_messages.each do |message|
        li = message
      end
  end

  table id='monte'
    tr
      td Start date
      td  = f.date_field :start_date, {:maxlength => '10', :size => '10'}
    tr
      td End date
      td  = f.date_field :end_date, {:maxlength => '10', :size => '10'}
    tr
      td Number of runs
      td = f.number_field :runs, {:min => '1'}
    tr
      td Trade type
      td = f.text_field :trade_type
    tr
      td Starting Amount
      td = f.number_field :starting_amount, {:min => '1000', :step => '.01'}
    tr
      td Minimum ticker price
      td = f.number_field :minimum_price, {:min => '0', :step => '.01'}
    tr
      td Maximum ticker price
      td = f.number_field :maximum_price, {:min => '1'}
    tr
      td Maximum number of picks
      td = f.number_field :max_picks, {:min => '1'}
    tr
      td Commission
      td = f.number_field :commission, {:min => '0', :step => '.01'}

  <br><br>

  div class="actions"
    = f.submit "Submit"
end

app/views/monte_carlo/home.html.slim
div class="center"
  h1 Stock Market Monte Carlo Simulation

= render 'form', monte_carlo: @monte_carlo 

app/views/monte_carlo/new.html.slim
div class="center"
  h1 Stock Market Monte Carlo Simulation

= render 'form', monte_carlo: @monte_carlo 

app/views/monte_carlo/show.html.slim
div class="center"
  h1 Stock Market Monte Carlo Simulation Show

= render 'form', monte_carlo: @monte_carlo

app/views/stss_trades/_form.html.erb
<%= form_with(model: stss_trade, local: true) do |form| %>
  <% if stss_trade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stss_trade.errors.count, "error") %> prohibited this stss_trade from being saved:</h2>

      <ul>
      <% stss_trade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stss_trades/_form.html.slim
= form_with(model: stss_trade, local: true) do |form|
  - if stss_trade.errors.any?
    div id="error_explanation"
      h2 = pluralize(stss_trade.errors.count, "error")
      | prohibited this stss_trade from being saved:

      ul
       - stss_trade.errors.full_messages.each do |message|
        li = message
      end
  end

  = form_for StssTrade.new do |f|
    = f.label :id
    = f.number_field :id
    = f.label :ticker
    = f.text_field :ticker
    = f.label :trade_type
    = f.text_field :trade_type
    = f.label :buy_date
    = f.date_field :buy_date
    = f.label :buy_price
    = f.number_field :buy_price, step: :any
    = f.label :sell_date
    = f.date_field :sell_date
    = f.label :sell_price
    = f.number_field :sell_price, step: :any
    = f.label :gain
    = f.number_field :gain, step: :any
    = f.label :days
    = f.number_field :days
  end

  div class="actions"
    = form.submit
end

app/views/stss_trades/edit.html.erb
<h1>Editing Stss Trade</h1>

<%= render 'form', stss_trade: @stss_trade %>

<%= link_to 'Show', @stss_trade %> |
<%= link_to 'Back', stss_trades_path %>

app/views/stss_trades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stss Trades</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stss_trades.each do |stss_trade| %>
      <tr>
        <td><%= link_to 'Show', stss_trade %></td>
        <td><%= link_to 'Edit', edit_stss_trade_path(stss_trade) %></td>
        <td><%= link_to 'Destroy', stss_trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stss Trade', new_stss_trade_path %>

app/views/stss_trades/index.html.slim
p id="notice"
  = notice

h1 Stss Trades

table
  thead
    tr
      th Trade Number
      th Ticker
      th Trade Type
      th Buy Date
      th Buy Price
      th Sell Date
      th Sell Price
      th Gain Percent
      th Days

  tbody
    tr
    - @stss_trades.each do |stss_trade|
      tr
        td = stss_trade.id
        td = stss_trade.ticker
        td = stss_trade.trade_type
        td = stss_trade.buy_date
        td = stss_trade.buy_price
        td = stss_trade.sell_date
        td = stss_trade.sell_price
        td = stss_trade.gain
        td = stss_trade.days
    end

= paginate @stss_trades

app/views/stss_trades/new.html.erb
<h1>New Stss Trade</h1>

<%= render 'form', stss_trade: @stss_trade %>

<%= link_to 'Back', stss_trades_path %>

app/views/stss_trades/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_stss_trade_path(@stss_trade) %> |
<%= link_to 'Back', stss_trades_path %>